name: Test SSH Connection

on:
  workflow_dispatch:
    inputs:
      pi_ip:
        description: 'Raspberry Pi IP Address'
        required: true
        default: '73.11.87.47'
      pi_port:
        description: 'SSH Port'
        required: true
        default: '2222'
      pi_user:
        description: 'SSH Username'
        required: true
        default: 'hayden'

env:
  PI_IP: ${{ github.event.inputs.pi_ip }}
  PI_PORT: ${{ github.event.inputs.pi_port }}
  PI_USER: ${{ github.event.inputs.pi_user }}

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    name: Test SSH Connection
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Adding host key to known_hosts..."
          ssh-keyscan -H -p ${{ env.PI_PORT }} ${{ env.PI_IP }} >> ~/.ssh/known_hosts
          echo "Verifying host key..."
          ssh-keyscan -H -p ${{ env.PI_PORT }} ${{ env.PI_IP }}

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection to ${{ env.PI_USER }}@${{ env.PI_IP }}:${{ env.PI_PORT }}"
          ssh -i ~/.ssh/id_rsa -p ${{ env.PI_PORT }} -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts ${{ env.PI_USER }}@${{ env.PI_IP }} "echo 'SSH connection successful!'"

      - name: Get system info
        run: |
          echo "Getting system information..."
          ssh -i ~/.ssh/id_rsa -p ${{ env.PI_PORT }} ${{ env.PI_USER }}@${{ env.PI_IP }} "
            echo '=== System Information ===' &&
            echo 'OS:' && cat /etc/os-release | grep PRETTY_NAME &&
            echo 'Python:' && python3 --version &&
            echo 'Memory:' && free -h &&
            echo 'Disk:' && df -h &&
            echo 'Uptime:' && uptime
          "
